version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: streamlit run frontend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  app_data: 